[package]
name = "undefended"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
inspector = ["bevy-inspector-egui"]

[dependencies]
bevy = "0.10.1"

bevy-tnua = { version = "0.2.1", features = ["rapier_3d"] }
bevy_rapier3d = { git = "https://github.com/dimforge/bevy_rapier", rev = "38e1b79169303c47d639d64558b7d9adeed99211", features = ["debug-render-3d"] }
bevy_dolly = { git = "https://github.com/BlackPhlox/bevy_dolly" }
bevy_asset_loader = "0.16.0"
bevy-inspector-egui = { version = "0.18.3", optional = true }
leafwing-input-manager = "0.9.1"
bevy-ui-navigation = "0.24.0"

rand = "0.8.5"
serde = "*"
ron = "0.8.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = {version="*", features = ["console", "Window", "Storage"]}

[patch.crates-io]
bevy_rapier3d = { git = "https://github.com/dimforge/bevy_rapier", rev = "38e1b79169303c47d639d64558b7d9adeed99211" }
