[package]
name = "undefended"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
inspector = ["bevy-inspector-egui"]
debugdump = ["bevy_mod_debugdump"]

[dependencies]
bevy = "0.11"
bevy-tnua = { version = "0.8", features = ["rapier_3d"] }
bevy_rapier3d = { version = "0.22", features = ["debug-render-3d"] }
bevy_dolly = { version = "0.0.1" }
bevy_asset_loader = "0.17.0"
bevy-inspector-egui = { version = "0.19", optional = true }
leafwing-input-manager = "0.10"
bevy-ui-navigation = "0.28.0"
bevy_mod_debugdump = { git = "https://github.com/rparrett/bevy_mod_debugdump", branch = "minimal-fix-18", optional = true }

rand = "0.8.5"
serde = "*"
ron = "0.8.0"
crossbeam-channel = "0.5.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = {version="*", features = ["console", "Window", "Storage"]}